### ISSUE TITLE
Default Build Parallelization

### ISSUE THREAD

**Issue by chvink** [mdaus/coda-oss#53]
I think we should consider setting a default number of parallel build jobs to 8 or even 4. Currently what I think waf is doing is just checking to see how many processors exist and using that many parallel jobs. This might be ok for personal/special systems but in shared environments this is just going to throttle _all_ the jobs and generally be inefficient.

**Comment by asylvest** [comment]
Yes, I believe waf is currently checking how many processors exist and using all available.  It would be slick if it took a look at the load on the system and tailored accordingly.  I think part of this is a user education problem too... if people are cognizant, they can use ```waf build -j4``` themselves.  So I guess it comes down to if we want unknowledgeable/lazy waf users to a) not take advantage of all the cores they could when a machine is quiet or b) unwittingly kill the system for everyone else on it when the machine is not quiet.

Personally I would rather keep things the way they are because I am really impatient and want everything to always go as fast as it can without thinking about it and philosophically I'm bummed out by not taking advantage of potentially idle cores.  But we can discuss if the consensus is on the other end.

@jmrandol @mbojrab @clydestanfield

**Comment by jmrandol** [comment]
Are we seeing performance degradation due to waf using too many resources?  If so, are we seeing waf competing with itself (other builds) or competing with other stuff?

Either way, I'm inclined to leave it alone, though we *could* throttle the Jenkins builds if there are too many.  We could also nice any Jenkins spawned processes on csd4600a (which I thought we had done).

-Jeff

________________________________

**Comment by mbojrab** [comment]
My preference is to leave it as is as well. I predominately do work on non-shared machines so I expect to destroy resource momentarily for my builds. As we move to AWS or 21st century hardware, this should be less of an issue. I think this comes down to engineers being mindful when they work on a shared resources not to kill it for everyone. I say all of this like I'm mindful of shared resources, Ha! ...but, this one goes to eleven ;p.
